# Generated by Django 5.1 on 2024-08-29 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='car_tex_number',
        ),
    ]
